# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    env:
      platform: aws
      region: us-east-1
      account: 123456789012

    runs-on: ubuntu-latest

    steps:
      - name: "Display message"
        run: echo "Hola Mundo"

      - name: "Mostrando variables de entorno"
        if: ${{ env.platform == 'azure'}}
        run: |
          echo "Esto es el valor de platform: ${{ env.platform }}"
          echo "Region: ${{ env.region }}"
          echo "Account:  ${{ env.account }}"

      - name: "Mostrando variables por defecto"
        run: |
          echo "Evento: ${{toJson(github.event)}}"